name: dsbridge_flutter
description: A modern cross-platform JavaScript bridge, through which you can invoke each other's functions synchronously or asynchronously between JavaScript and Dart.
version: 1.0.1
homepage: https://github.com/gtbluesky/dsbridge_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter_platform_interface: ^2.9.0
  webview_flutter: ^4.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # pana: ^0.21.25

topics:
  - jsbridge
  - javascript
  - webview
  - html