name: dsbridge
description: A modern cross-platform JavaScript bridge, through which you can invoke each other's functions synchronously or asynchronously between JavaScript and Dart.
version: 1.0.0
homepage: https://github.com/gtbluesky/dsbridge_flutter

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter:
    git:
      url: https://github.com/jsharp83/packages
      path: packages/webview_flutter/webview_flutter
      ref: add-javascript-panel-interface

dependency_overrides:
  webview_flutter_android:
    git:
      url: https://github.com/jsharp83/packages
      path: packages/webview_flutter/webview_flutter_android
      ref: add-javascript-panel-interface
  webview_flutter_wkwebview:
    git:
      url: https://github.com/jsharp83/packages
      path: packages/webview_flutter/webview_flutter_wkwebview
      ref: add-javascript-panel-interface
  webview_flutter_platform_interface:
    git:
      url: https://github.com/jsharp83/packages
      path: packages/webview_flutter/webview_flutter_platform_interface
      ref: platform-interface-for-javascript-panel

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

topics:
  - jsbridge
  - javascript
  - webview
  - html